#!/bin/bash

sudo apt-get update
sudo apt-get upgrade

sudo apt-get install  \
  grive               \
  chromium-browser    \
  freemind            \
  libreoffice         \
  lyx                 \
  texlive-full        \
  luatex              \
  sublime-text        \
  netbeans            \
  sqlite3             \
  sqlitebrowser       \
  mysql-client-5.6    \
  mysql-server-5.6    \
  mysql-workbench     \
  git                 \
  git-gui             \
  make                \
  cmake               \
  python2.7           \
  python-pysqlite2    \
  idle-python2.7      \
  python3.4           \
  python3-dateutil    \
  python3-yaml        \
  python3-numpy       \
  python3-matplotlib  \
  python3-numexpr     \
  python3-sql         \
  python3-apsw        \
  idle-python3.4      \
  ruby2.0             \
  ruby-narray         \
  apache2             \
  php5                \
  php5-curl           \
  php5-json           \
  php5-mysql          \
  php5-sqlite         \
  php-pear            \
  phpunit             \
  octave              \
  rstudio             \
  gnuplot             \
  gnuplot-qt          \
  gnuplot-x11         \
  oaklisp             \
  mit-scheme          \
  ghc                 \
  paraview            \
  gcc-4.9-base        \
  g++-4.8             \
  clang-3.5           \
  clang-format-3.5    \
  clang-modernize-3.5 \
  gdb                 \
  gdb64               \
  valgrind            \
  valkyrie            \
  kcachegrind         \
  tau                 \
  google-perftools    \
  libgoogle-perftools-dev \
  libgoogle-perftools4    \
  graphviz            \
  gv                  \
  cppcheck            \
  qt5-default         \
  qt5-qmake           \
  qt4-default         \
  qt4-designer        \
  qt4-qmake           \
  openmpi-bin         \
  libopenmpi-dev      \
  libopenmpi1.6       \
  libopencv-dev       \
  libopencv-gpu-dev   \
  libopencv-gpu2.4    \
  libopencv-core2.4   \
  libgtest-dev        \
  libvtk6             \
  libvtk6-dev         \
  libsqlite3-0        \
  libsqlite3-dev      \
  libmysqlclient-dev  \
  libmysqlclient18    \
  libgtk-3-0          \
  libgtk-3-dev        \
  libgtksourceview-3.0-1    \
  libgtksourceview-3.0-dev  \
  libcairo2           \
  libcairo2-dev       \
  libyaml-cpp-dev     \
  libyaml-cpp0.3      \
  libjson-c-dev       \
  libyajl2            \
  libyajl-dev         \
  yajl-tools          \
  libjansson-dev      \
  libjansson4         \
  libjaula-dev        \
  libjaula1           \
  libblas-dev         \
  libblas3            \
  libatlas3           \
  liblapack-dev       \
  liblapack3          \
  libeigen3-dev       \
  libarpack2-dev      \
  libarmadillo-dev    \
  libboost1.55-all-dev
  
sudo apt-get remove firefox thunderbird
