#!/usr/bin/env python

import sys

if len(sys.argv) < 2:
    print 'usage: countlines filename (filename2) (...)'

else:

    print ''
    for i in range(1, len(sys.argv)):
        try:
            f = open(sys.argv[i])
            print '%(fname)25s:     %(n)d' % {'fname' : sys.argv[i], \
                                              'n' : len(f.readlines())}
            f.close()
        except:
            print 'Could not open', sys.argv[i]
